<?php

declare(strict_types=1);

namespace Tests\Select;

use Isterkh\QueryBuilder\QB;
use Tests\QueryTestTemplate;

abstract class SelectQueryTestTemplate extends QueryTestTemplate
{
    protected QB $query;
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->query = (clone $this->builder)->select()->from('t');
    }
}
