<?php

declare(strict_types=1);

namespace Tests\MySql\SelectQuery;

use Isterkh\QueryBuilder\Queries\SelectQuery;
use Tests\MySql\QueryTestTemplate;

abstract class SelectQueryTestTemplate extends QueryTestTemplate
{
    protected SelectQuery $query;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->query = $this->builder->select()->from('t');
    }
}
