<?php

declare(strict_types=1);

namespace Tests;

use Isterkh\QueryBuilder\Compilers\SqlCompiler;
use Isterkh\QueryBuilder\QB;
use PHPUnit\Framework\TestCase;

abstract class QueryTestTemplate extends TestCase
{
    protected QB $builder;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->builder = new QB(
          new FakeConnection(
              new SqlCompiler()
          ),
        );
    }
}
