<?php

declare(strict_types=1);

namespace Tests;

use Isterkh\QueryBuilder\Compilers\Grammar\MySqlGrammar;
use Isterkh\QueryBuilder\Compilers\SqlCompiler;
use Isterkh\QueryBuilder\QueryBuilder;
use PHPUnit\Framework\TestCase;

abstract class QueryTestTemplate extends TestCase
{
    protected QueryBuilder $builder;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->builder = new QueryBuilder(
          new FakeConnection(
              new SqlCompiler(new MySqlGrammar())
          ),
        );
    }
}
