<?php

declare(strict_types=1);

namespace Tests\MySql;

use Isterkh\QueryBuilder\Compilers\Compiler;
use Isterkh\QueryBuilder\Compilers\Grammar\MySqlGrammar;
use Isterkh\QueryBuilder\QueryBuilder;
use PHPUnit\Framework\TestCase;
use Tests\FakeConnection;

abstract class QueryTestTemplate extends TestCase
{
    protected QueryBuilder $builder;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->builder = new QueryBuilder(
            new FakeConnection(
                new Compiler(new MySqlGrammar())
            ),
        );
    }
}
