<?php
declare(strict_types=1);


namespace Tests\MySql;

use Isterkh\QueryBuilder\Compilers\MySql\ConditionsCompiler;
use Isterkh\QueryBuilder\Compilers\MySql\SelectQueryCompiler;
use Isterkh\QueryBuilder\QueryBuilder;
use PHPUnit\Framework\TestCase;

abstract class QueryTestTemplate extends TestCase
{
    protected QueryBuilder $builder;
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->builder = new QueryBuilder(
            new SelectQueryCompiler(new ConditionsCompiler())
        );
    }
}