<?php

declare(strict_types=1);

namespace Tests\MySql;

use Isterkh\QueryBuilder\QueryBuilder;

abstract class SelectQueryTestTemplate extends QueryTestTemplate
{
    protected QueryBuilder $selectQuery;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->selectQuery = (clone $this->builder)->select()->from('t');
    }
}
